version: '3.9'
services:
  octordle_nginx:
    image: nginx
    container_name: octordle_nginx
    depends_on:
      - octordle_server
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/ssl/cert.pem
      - ./privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - 80:80
      - 443:443
  octordle_server:
    image: octordle_server:latest
    container_name: octordle_server
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_DOMAIN=postgres
    restart: always
    ports:
      - 5000:5000
  postgres:
    image: postgres
    container_name: db
    env_file:
      - ./.env
    volumes:
      - ./demodb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432